name: MSUA
author: balugaq
main: com.balugaq.msua.MSUA
website: https://github.com/balugaq/MSUA
version: ${project.version}
api-version: 1.20
softdepend:
  - Slimefun
  - Rebar
commands:
  msua:
    description: MSUA base command

permissions:
  msua.admin:
    description: Allows you to use all MSUA commands
    default: op
